package:
    name: pylauncher
    version: 1.0.0
source:
    git_url:  https://github.psi.ch/scm/cos/pylauncher.git
requirements:
    build:
        - python
        - setuptools
        - pyqt
    run:
        - python
        - pyqt
about:
    home: https://github.psi.ch/projects/COS/repos/pylauncher/browse
    license: GPL3+
    summary: "Standard PSI launcher application."