package:
    name: pylauncher
    version: v0.9.3
source:
    git_tag: v0.9.3
    git_url: https://github.psi.ch/scm/cos/pylauncher.git
requirements:
    build:
        - python
        - setuptools
        - pyqt
        - pyparsing
    run:
        - python
        - pyqt
        - pyparsing

build:
  entry_points:
    - pylauncher = pylauncher.launcher:main
    - pylauncher-convert = pylauncher.convert.convert:main

about:
    home: https://github.psi.ch/projects/COS/repos/pylauncher/browse
    summary: "Standard PSI launcher application."
