package:
    name: launcher
    version: v0.9.0
source:
    git_rev: v0.9.0
    git_url:  https://github.psi.ch/scm/cos/pylauncher.git
requirements:
    build:
        - python
        - setuptools
        - pyqt
        - qt
        - pyparsing
    run:
        - python
        - pyqt
        - qt
        - pyparsing

build:
  entry_points:
    - launcher = pylauncher.launcher:main
    - launcher-convert = pylauncher.convert.convert:main

about:
    home: https://github.psi.ch/projects/COS/repos/pylauncher/browse
    summary: "Standard PSI launcher application."